name: PressurePlateTest
main: io.github.cmansfield.PressurePlateTest.PressurePlateTest
version: 0.0.1
author: AirsoftingFox
description: A Pressure Plate test Plugin
commands:
    ppEnable:
        description: Walk over pressure plates without engaging them
        usage: /ppEnable
    ppDisable:
        description: Allow pressure plates to trigger again
        usage: /ppDisable