#_______________________________________________________________
#                                                               
#                        MystAFK Config                         
#                                                               
#_______________________________________________________________

# The format for rank changes is


# Time in seconds until the player receives an AFK
# prompt in chat
PromptTime: 3300

# This value is the time in seconds until a player is
# automatically placed into an AFK state
TimeOutTime: 3600

# Boolean value. If this value is set to true then
# player movement will reset their AFK timer
MoveResetTimer: false
messages:
    ArmorStandEditErrMsg: You cannot edit this at this time
    NoAFKkeyErrMsg: You are not permitted to use this command
    PlayerNotAFK: Good to know you're not AFK
    PlayerNoLongerAFK: \p is no longer AFK
    PlayerIsNowAFK: \p is now AFK
    PlayerTag: AFK
    ActionBarMsg: WARNING! You are about to be set to AFK!
    ChatPrompt: You've been playing for awhile, are you AFK?
    ChatClickText: I am not AFK
    NoCommandMsg: You cannot use commands while you are AFK
    PvtMsgErr: You cannot send private messages to AFK players