#_______________________________________________________________
#                                                               
#                        MystAFK Config                         
#                                                               
#_______________________________________________________________

# The format for rank changes is


# Time in seconds until the player receives an AFK
# prompt in chat
PromptTime: 3300

# This value is the time in seconds until a player is
# automatically placed into an AFK state
TimeOutTime: 3600

# Default kick time is 1 1/2 hours
KickTimeOut: 5400

# Boolean value. If this value is set to true then
# player movement will reset their AFK timer
MoveResetTimer: false
KickCommands: 
    - time set day
    - say \p was kicked for being AFK
    - test command 3
messages:
    ArmorStandEditErrMsg: You cannot edit this at this time
    NoAFKkeyErrMsg: You are not permitted to use this command
    PlayerNotAFK: Good to know you're not AFK
    PlayerNoLongerAFK: \p is no longer AFK
    PlayerIsNowAFK: \p is now AFK
    PlayerTag: AFK
    ActionBarAFKmsg: WARNING! You will be set to AFK in \s seconds!
    ActionBarKickmsg: WARNING! You've been idle for too long, you will be kicked in \s seconds!
    ActionBarYouAreAFK: You have been AFK for \s seconds
    ChatPrompt: You've been playing for awhile, are you AFK?
    ChatClickText: I am not AFK
    NoCommandMsg: You cannot use commands while you are AFK
    PvtMsgErr: You cannot send private messages to AFK players