name: MystAFK
main: io.github.cmansfield.MystAFK.MystAFK
version: 0.1.4
author: AirsoftingFox
description: A custom AFK plugin for http://mystserver.enjin.com/
commands:
    AFK:
        description: Toggles a player's AFK status
        usage: /AFK
    NoAFK:
        description: Tells the server that a player is active, not to used manually by players
        usage: NO ACTION
        
permissions:
    mystafk.*:
        description: Gives access to all permissions of MystAFK.
        default: op
        children:
            mystafk.bypassAFK: true
    mystafk.bypassAFK:
        description: Makes a player exempt from the AFK checks
        default: op